# Generated by Django 5.1.1 on 2024-09-10 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_price_per_person_per_night', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('weekend_price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('seasonal_price_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('villa_type', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rental.villa')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='rental.villa')),
            ],
        ),
    ]
