# Generated by Django 5.1.1 on 2024-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='extra_price_per_person_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
