# Generated by Django 5.1.1 on 2024-09-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_villa_extra_price_per_person_per_night'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='seasonal_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='villa',
            name='weekend_price_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=4),
        ),
    ]
